config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  devise_for :users
  resources :users, only: [:show]

  resources :articles do
    collection do
      get :search
    end
    resources :comments, only: [:new, :edit, :create, :update, :destroy] do
      resources :comment_likes, only: [:create, :destroy]
    end
    resources :stocks, only: [:create, :destroy]
    resources :article_likes, only: [:create, :destroy]
  end

  resources :groups do
    resources :group_users, only: [:new, :create, :update, :destroy]
    resources :managers, only: [:update] do
      collection do
        get :change_manager
      end
    end
  end

  match 'tags/:tag', to: 'articles#index', as: :tag, via: [:get, :post]
  get 'tags', to: 'tags#index'

  post 'api_markdown' => 'articles#api_markdown'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
  has_many :article_likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :stocks, dependent: :destroy

  validates :title, presence: true, uniqueness: true
  validates :body, presence: true
  validates :user_id, presence: true
  validates :group_id, presence: true

  # グループとの関連付けに関するscope
  scope :available_to, ->(user) { where(group_id: user.groups.map(&:id)) }
  scope :body_include, ->(keyword) { where('body LIKE ?', "%#{keyword}%") }

  # userを引数にして、そのuserがcommentしたarticleを持ってくる
  scope :commented_by, ->(user) { where(id: user.comments.map(&:article_id)) }

  # articleのいいね機能に関するメソッド
  def user_like(user_id)
    article_likes.find_by(user_id: user_id)
  end

  # articleのtag機能に関するメソッド
  acts_as_taggable
  acts_as_taggable_on :labels

  # stockに関するメソッド
  def stocked?(user)
    Stock.exists?(user_id: user.id, article_id: id)
  end

  def related_stock(user)
    stocks.find_by(user_id: user.id)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :protect_private_article, only: [:show, :edit, :update, :destroy]
  before_action :confirm_permission, only: [:edit, :update, :destroy]

  def index
    viewable_articles = Article.available_to(current_user)
    @tag = params[:tag] if params[:tag]
    @articles = if params[:tag]
                  viewable_articles
                    .tagged_with(params[:tag])
                    .order('updated_at DESC')
                    .page(params[:page])
                    .per(10)
                else
                  viewable_articles
                    .order('updated_at DESC')
                    .page(params[:page])
                    .per(10)
                end
  end

  def show
    @comment = Comment.new
    @comments = @article.comments
    @stock = Stock.new
    @article_like = ArticleLike.find_by(
      user_id: current_user.id,
      article_id: params[:article_id]
    )
  end

  def new
    @group = if params[:group_id]
               Group.find(params[:group_id])
             else
               Group.find(Group::MASTER_GROUP_ID)
             end
    @article = Article.new
  end

  def edit; end

  def create
    @article = Article.new(article_params)
    if @article.save
      if @article.group.private == false
        Slack.chat_postMessage(
          text: "#{current_user.username} created #{@article.title}!",
          username: 'Mr.Qiita Team',
          channel: SLACK_SHARE_CHANNEL
        )
      end
      redirect_to @article, notice: 'Your Article are successfuly posted'
    else
      @group = if params[:group_id]
                 Group.find(params[:group_id])
               else
                 Group.find(Group::MASTER_GROUP_ID)
               end
      flash.now[:alert] = 'Some errors occured'
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Your Article are successfuly updated'
    else
      flash.now[:alert] = 'Some errors occured'
      render 'edit'
    end
  end

  def destroy
    @article.tag_list = {}
    @article.destroy
    redirect_to root_path
  end

  def search
    @keyword = params[:keyword]
    viewable_articles = Article.available_to(current_user)
    @articles = viewable_articles
                .body_include(params[:keyword])
                .order('updated_at DESC')
                .page(params[:page])
                .per(10)
    respond_to do |format|
      format.js
    end
  end

  private

  def article_params
    params.require(:article).permit(
      :title,
      :body,
      :tag_list,
      :group_id
    ).merge(user_id: current_user.id)
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def protect_private_article
    unless @article.group.private && @article.group.users.include?(current_user)
      redirect_to root_path, alert: "You don't have a permission to refer this group"
    end
  end

  def confirm_permission
    redirect_to '', alert: 'You do not have a permission' unless @article.user == current_user
  end
end

app/views/articles/_article_like.html.erb
<% if article.user_like(current_user.id) %>
  <%= button_to article_article_like_path(article, article.user_like(current_user.id)),
    method: :delete,
    class: "like-button article__like-button",
    remote: true  do
  %>
    <%= fa_icon "thumbs-up"%> | <%= article.likes_count %>Liked
  <% end %>
<% else %>
  <%= button_to article_article_likes_path(article),
    class: "like-button article__like-button",
    remote: true do
  %>
    <%= fa_icon "thumbs-o-up"%> | <%= article.likes_count %>Liked
  <% end %>
<% end %>

app/views/articles/_articles.erb
<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>投稿者</th>
      <th>投稿先(グループ名)</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to article.title, article_path(article) %></td>
        <td><%= article.user.username %></td>
        <td>
          <% unless article.group_id == MASTER_GROUP_ID %>
            <%= link_to article.group.name, article.group %>
          <% else %>
            全員に公開
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/_comment_form.html.erb
<div class='comment'>
  <div class='comment-user'>
  <%= image_tag current_user.image.to_s, class: 'comment-user__image' %>
    <div class='comment-user__name'>
      <%= current_user.username %>
    </div>
  </div>
  <div class='comment-body'>
      <%= form_for [article, comment], remote: true do |f| %>
        <%= f.text_area :body,
          placeholder: 'write comment',
          rows: 5,
          class: 'comment__textarea'
        %>
        <%= f.submit "submit", class: 'comment__submit' %>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/_comment_like.html.erb
<div id ='comment_like-buttons-<%= comment.id %>'>
  <% if comment.user_like(current_user.id) %>
    <%= button_to article_comment_comment_like_path(@article, comment, comment.user_like(current_user)),
      method: :delete, class: "like-button comment__like-button",
      remote: true do
    %>
      <%= fa_icon "thumbs-up"%> | <%= comment.likes_count %>Liked
    <% end %>
  <% else %>
    <%= button_to article_comment_comment_likes_path(@article, comment),
      class: "like-button comment__like-button",
      remote: true do
    %>
      <%= fa_icon "thumbs-o-up"%> | <%= comment.likes_count %>Liked
    <% end %>
  <% end %>
</div>

app/views/articles/_comments.html.erb
<% comments.each do |comment| %>
  <div class='comment'>
    <div class='comment-user'>
      <%= image_tag comment.user.image.to_s, class: 'comment-user__image' %>
      <div class='comment-user__name'>
        <%= comment.user.username %>
      </div>
      <div class='comment--right  clearfix'>
        <div class='comment__buttons'>
          <% if current_user == comment.user %>
            <%= link_to "Edit",
              edit_article_comment_path(article, comment),
              class: "comment__button comment__edit-button>",
              remote: true
            %>
            <%= link_to "Delete",
              article_comment_path(article, comment),
              method: :delete,
              class: 'comment__button comment__delete-button',
              remote: true,
              data: { confirm: 'Are you sure to delete this comment?'}
            %>
          <% end %>
        </div>
        <div class='comment__updated-at'>
          <%= comment.updated_at.in_time_zone('Tokyo').to_s(:usual_format) %>
        </div>
      </div>
    </div>
    <div class='comment-body'>
      <div class='comment__sentence'>
        <%= comment.body %>
      </div>
      <div class='comment-footer'>
        <%= render partial: "articles/comment_like",
          locals:  { article: article, comment: comment }
        %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_result.erb
<%= javascript_include_tag 'cut_string' %>
<div class='searched-articles-container'>
  <% if keyword.present? || keyword.nil? %>
    <% if keyword.present? %>
      <p>The result of search by keyword "<%= @keyword %>"</p>
    <% end %>
    <div class='searched-articles'>
      <% articles.each do |article| %>
        <%  unless article.group.private && article.group.users.include?(current_user) == false %>
          <div class='searched-article'>
            <%= image_tag article.user.image.to_s, class: 'searched-article__image' %>
            <div class='searched-article__body'>
              <div class='searched-article__body__header'>
                <span class='searched-article__username'>
                  by <%= link_to article.user.username, user_path(article.user) %>
                </span>
              </div>
              <div class='searched-article__body__footer'>
                <div class='searched-article__title'>
                  <%= link_to article.title, article_path(article), class: 'cut_string' %>
                </div>
                <!-- groupの性質によってstyleを分ける -->
                <% if article.group.private == true %>
                  <div class='searched-articie__statement' style='background-color: #d94;'>
                    <%= fa_icon 'key' %> <%= link_to article.group.name, article.group %>
                  </div>
                <% elsif article.group_id == Group::MASTER_GROUP_ID %>
                  <div class='searched-article__statement' style='background-color: #3b6;'>
                    Public
                  </div>
                <% else %>
                  <div class='searched-article__statement' style='background-color: #5bd;'>
                    <%= fa_icon 'group' %> <%= link_to article.group.name, article.group %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
      <div class='pagination-container'>
        <%= paginate articles %>
      </div>
    </div>
  <% else %>
    <p>type some keyword!!</p>
  <% end %>
</div>

app/views/articles/_result.html.erb
<% if keyword.nil? %>
  <h3>Timeline</h3>
<% elsif keyword.empty? %>
  <h3>キーワードを入力してください</h3>
<% else %>
  <h3>"<%= keyword %>"で検索した結果</h3>
<% end %>
<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>投稿者</th>
      <th>投稿先(グループ名)</th>
    </tr>
  </thead>

  <tbody>
    <% articles.each do |article| %>
      <tr>
        <td><%= link_to article.title, article_path(article) %></td>
        <td><%= article.user.username %></td>
        <td>
          <% unless article.group_id == MASTER_GROUP_ID %>
            <%= link_to article.group.name, article.group %>
          <% else %>
            全員に公開
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/_top_tabs.html.erb
<div class='top-tabs'>
  <%= link_to "Timeline", :root, method: :get, class: 'top-tab' %>
  <%= link_to "Tags", tags_path,method: :get, class: 'top-tab' %>
  <%= link_to "Groups", groups_path, method: :get, class: 'top-tab' %>
</div>

app/views/articles/edit.html.erb
<%= javascript_include_tag 'articles/preview' %>

<% if @article.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @article do |f| %>
  <div class='article-editor'>
    <div class='article-editor__title'>
      <%= f.text_field :title,
        placeholder: "Title",
        class: 'article-editor__thin-form article-editor__title__form'
      %>
    </div>
    <div class='article-editor__tags'>
      <%= text_field_tag 'article[tag_list]',
        @article.tag_list.join(','),
        'data-role'=>'tagsinput',
        placeholder: "Write Tag Name and Push Enters",
        class: 'article-editor__thin-form article-editor__tags__form'
      %>
    </div>
    <div class='article-editor__bodies'>
      <div class='article-editor__body'>
        <%= f.text_area :body,
          placeholder: "write body with Markdown",
          class: 'article-editor__body__form'
        %>
      </div>
      <div id='preview--container' class='article-editor__preview'>
        <!-- ここにjsでpreview表示する -->
      </div>
    </div>
    <div class='article-editor__submit'>
      <%= f.submit "Update", class: 'article-editor__submit-button' %>
    </div>
  </div>
<% end %>

app/views/articles/index.html.erb
<%= render partial: 'articles/top_tabs' %>

<div class='title-container'>
  <% if @tag %>
    <p class='tab-title'>Articles tagged to <%= @tag %></p>
  <% else %>
    <p class='tab-title'>Timeline</p>
  <% end %>
</div>

<div class='form-container'>
    <%= form_tag(search_articles_path, method: :get, class: 'searching__form', remote: true) do %>
      <%= text_field_tag :keyword, "", placeholder: 'search article', class: 'searching__keyword' %>
      <%= button_tag type="submit", name: nil, class: 'searching__submit' do %>
        <%= fa_icon "search" %> search
      <% end %>
    <% end %>
</div>

<div class='searched-results'>
    <%= render partial: 'result', locals: { articles: @articles, keyword: nil } %>
</div>

app/views/articles/new.html.erb
<%= javascript_include_tag 'articles/preview' %>

<% if @article.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @article do |f| %>
  <div class='article-editor'>
    <div class='article-editor__title'>
      <%= f.text_field :title,
        placeholder: "Title",
        class: 'article-editor__thin-form article-editor__title__form'
      %>
    </div>
    <div class='article-editor__tags'>
      <%= text_field_tag 'article[tag_list]',
        @article.tag_list.join(','),
        'data-role'=>'tagsinput',
        placeholder: "Write Tag Name and Push Enters",
        class: 'article-editor__thin-form article-editor__tags__form'
      %>
    </div>
    <div class='article-editor__bodies'>
      <div class='article-editor__body'>
        <%= f.text_area :body,
          placeholder: "write body with Markdown",
          class: 'article-editor__body__form'
        %>
      </div>
      <div id='preview--container' class='article-editor__preview'>
        <!-- ここにjsでpreview表示する -->
      </div>
    </div>
    <%= f.hidden_field :group_id, value: @group.id %>
    <div class='article-editor__submit'>
      <% if @group.id == Group::MASTER_GROUP_ID %>
        <%= f.submit "Post to everyone", class: 'article-editor__submit-button' %>
      <% else %>
        <%= f.submit "Post in #{@group.name}", class: 'article-editor__submit-button' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/articles/preview.js.erb
$("#preview").html("<%= j(render partial: 'preview', locals: { article: @previewed_article })  %>")

app/views/articles/search.js.erb
$(".searched-results").html("<%= j(render partial: 'articles/result', locals: { articles: @articles, keyword: @keyword }) %>")

app/views/articles/show.html.erb
<div class='article-viewer'>
  <div class='article'>

    <div class='article-header'>
      <%= image_tag @article.user.image.to_s, class: 'article-user__image' %>
      <div class='article__information'>
        <div class='article__user-name'>
          <%= link_to @article.user.username, @article.user %>
        </div>
        <div class='article__updated-at'>
          <%= @article.updated_at.in_time_zone('Tokyo').to_s(:usual_format) %>
        </div>
      </div>
      <div class='article__header--right'>
        <% if @article.stocked?(current_user) %>
          <%= link_to article_stock_path(@article, @article.related_stock(current_user)),
            method: :delete,
            class: 'article__stock-button' do
          %>
            <%= fa_icon "folder-open" %> | unstock
          <% end %>
        <% else %>
          <%= link_to article_stocks_path(@article, @stock),
            method: :post,
            class: 'article__stock-button' do
          %>
            <%= fa_icon "folder-open-o" %> | stock
          <% end %>
        <% end %>
        <!-- 書いた本人なら編集と削除のボタンを表示 -->
        <% if current_user == @article.user %>
          <%= link_to "Edit",
            edit_article_path(@article),
            method: :get,
            class: 'article__edit-button'
          %>
          <%= link_to "Delete",
            @article,
            method: :delete,
            class: 'article__delete-button',
            data: { confirm: 'Are you sure to delete this artivcl'}
          %>
        <% end %>
      </div>
    </div>

    <div class='article-main'>
      <div class='article__title'>
        <%= @article.title %>
      </div>

      <div class='article__body'>
        <%= markdown(@article.body).html_safe %>
      </div>
      <!-- タグをそれぞれリンクにして表示 -->
      <div class='article__tags', style="display:inline-flex">
        <div class='article__tags__label'>Tags：</div>
        <%= raw @article.tag_list.map { |t| link_to t, tag_path(t), class: 'article__tag' }.join('') %>
      </div>
    </div>

    <div class='article-footer'>
      <!-- LikeとUnlikeを切り替える -->
      <div id='article_like-buttons'>
        <%= render partial: "article_like", locals: { article: @article }  %>
      </div>
    </div>
  </div>

  <div class='comments-container'>
    <div class="comments">
      <%= render partial: 'comments', locals: { article: @article, comments: @comments } %>
    </div>
    <div class='comment-form'>
      <%= render partial: 'comment_form', locals: { article: @article, comment: @comment } %>
    </div>
  </div>
</div>