config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  devise_for :users
  resources :users, only: [:show]

  resources :articles do
    collection do
      get :search
    end
    resources :comments, only: [:new, :edit, :create, :update, :destroy] do
      resources :comment_likes, only: [:create, :destroy]
    end
    resources :stocks, only: [:create, :destroy]
    resources :article_likes, only: [:create, :destroy]
  end

  resources :groups do
    resources :group_users, only: [:new, :create, :update, :destroy]
    resources :managers, only: [:update] do
      collection do
        get :change_manager
      end
    end
  end

  match 'tags/:tag', to: 'articles#index', as: :tag, via: [:get, :post]
  get 'tags', to: 'tags#index'

  post 'api_markdown' => 'articles#api_markdown'

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :group_users
  has_many :users, through: :group_users
  has_many :articles, dependent: :destroy
  has_one :manager

  validates :name, presence: true
  validates :body, presence: true
  validates :manager_id, presence: true

  MASTER_GROUP_ID = 1

  def relation_with_user(user)
    group_users.find_by(user_id: user.id)
  end

  def joined_by_this_user?(user)
    GroupUser.exists?(user_id: user.id, group_id: id)
  end

  def self.without_master_joined_by(user)
    user.groups - [ find(MASTER_GROUP_ID) ]
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :prevent_using_master_group, only: [:show, :edit, :update, :destroy]
  before_action :confirm_permission, only: [:edit, :update, :destroy]

  def index; end

  def show
    @group = Group.find(params[:id])
    # グループがprivateの場合、メンバーじゃない人を弾く
    if @group.private && @group.users.include?(current_user) == false
      redirect_to groups_path, alert: "You don't have a permission to refer this group"
    end
    @group_user = GroupUser.new
  end

  def new
    @group = Group.new
    @group_user = GroupUser.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      @group.users << current_user
      redirect_to @group, notice: 'New Group was Successfuly created'
    else
      flash.now[:alert] = 'Some errors occured'
      render 'new'
    end
  end

  def edit; end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to @group, notice: "Group #{@group.name} was Successfuly created"
    else
      flash.now[:alert] = 'Some errors occured'
      render 'edit'
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :body, :private).merge(manager_id: current_user.id)
  end

  # Groupクラスのインスタンス変数を定義
  def set_group
    @group = Group.find(params[:id])
  end

  # masterグループにURLから処理を行おうとするのを防ぐ
  def prevent_using_master_group
    return unless @group.id == Group::MASTER_GROUP_ID
    redirect_to groups_path, notice: 'Not Found'
  end

  # 紐づいていないuserが編集や削除をするのを防ぐ
  def confirm_permission
    redirect_to groups_path unless current_user.groups.include?(@group)
  end
end

app/views/groups/_sidebar.html.erb
<div class='group-sidebar'>
  <div class='group-sidebar__header'>
    <div class='group__name'>
      <% if @group.private == true %>
        <%= fa_icon 'key' %> <%= @group.name %>
      <% else %>
        <%= fa_icon 'group' %> <%= @group.name %>
      <% end %>
    </div>
    <div class='group-sidebar__body'>
      <div class='group__body'>
        <%= @group.body %>
      </div>
      <p class='group__manager'>
        Manager：<%= link_to User.group_manager(@group.manager_id).username, user_path(User.group_manager(@group.manager_id).id) %>
      </p>
    </div>
    <div class='group-sidebar__footer'>
      <% if @group.manager_id == current_user.id %>
        <!-- 管理者だけが編集できる -->
        <%= link_to 'Edit', edit_group_path(@group), method: :get %>
        <!-- 管理者だけが踏める削除ボタン -->
        <%= link_to "Delete", @group, method: :delete %>
        <!-- 管理者だけが踏める管理者権限の譲渡フォームへのリンク -->
        <%= link_to 'Change Manager', change_manager_group_managers_path(@group), method: :get %>
      <% else %>
        <!-- 管理者はグループを抜けられない（抜けたら終わるから） -->
        <% if @group.joined_by_this_user?(current_user) %>
          <!-- すでに参加していたらグループ抜けるボタン -->
          <%= link_to 'Leave from this Group',
            [@group, @group.relation_with_user(current_user)],
            method: :delete,
            data: { confirm: 'Are you sure to leave from this Group'}
          %>
        <% else %>
          <!-- 参加していなかったら参加ボタン -->
          <%= link_to 'Join this Group',
            group_group_users_path(user_id: current_user.id, group_id: @group.id),
            method: :post
          %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/edit.html.erb
<div class='group-editor__container'>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @group.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class='group-editor'>
    <%= form_for @group do |f| %>
      <div class='group-editor__title'>Edit Group</div>
      <div class='forms'>
        <%= f.label :name, "Group Name" %>
        <%= f.text_field :name %>
      </div>
      <div class='forms'>
        <%= f.label :body, "About this Group" %>
        <%= f.text_field :body %>
      </div>
      <div class='forms_checkbox'>
        <%= f.check_box :private, {}, 'true', 'false' %>
        <%= f.label :private, "Make this group Private?" %>
        <p>In 'Private' groups, only members can read articles</p>
      </div>
      <div class='actions'>
        <%= f.submit "Update" %>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/index.html.erb
<%= render partial: 'articles/top_tabs' %>

<div class='title-container'>
  <p class='tab-title'>Groups</p>
</div>

<div class='groups-container'>

  <div class='groups__header'>
    <%= link_to "Create New Group",
      new_group_path(),
      method: :get,
      class: 'group__create-button'
    %>
  </div>

  <ul class="nav nav-tabs">
    <li class="active">
      <a href="#tab1" class="nav-link" data-toggle="tab">
        Your Groups
      </a>
    </li>
    <li>
      <a href="#tab2" class="nav-link" data-toggle="tab">
        Groups You Can Join
      </a>
    </li>
  </ul>

  <div class="tab-content">
    <div id="tab1" class="tab-pane active">
      <% if current_user.belonging_groups_without_master.present? %>
        <% current_user.belonging_groups_without_master.each do |group| %>
          <div class='group'>
            <div class='group__name'>
              <% if group.private == true %>
                <%= fa_icon 'key' %> <%= link_to group.name, group_path(group) %>
              <% else %>
                <%= fa_icon 'group' %> <%= link_to group.name, group_path(group) %>
              <% end %>
            </div>
            <div class='group__statement'>
              <%= fa_icon 'file-text-o' %> <%= group.articles.length %>
              <%= fa_icon 'user-circle' %> <%= group.users.length %>
            </div>
          </div>
        <% end %>
      <% else %>
        <p>You haven't joined any groups</p>
      <% end %>
    </div>
    <div id="tab2" class="tab-pane">
      <% if current_user.not_belonging_public_groups.present? %>
        <% current_user.not_belonging_public_groups.each do |group| %>
          <div class='group'>
            <div class='group__name'>
              <% if group.private == true %>
                <%= fa_icon 'key' %> <%= link_to group.name, group_path(group) %>
              <% else %>
                <%= fa_icon 'group' %> <%= link_to group.name, group_path(group) %>
              <% end %>
            </div>
            <div class='group__statement'>
              <%= fa_icon 'file-text-o' %> <%= group.articles.length %>
              <%= fa_icon 'user-circle' %> <%= group.users.length %>
            </div>
            <%= link_to 'Join', group_group_users_path(user_id: current_user.id, group_id: group.id), method: :post %>
          </div>
        <% end %>
      <% else %>
       <p>There are no groups you can join in</p>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class='group-editor__container'>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @group.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class='group-editor'>
    <%= form_for @group do |f| %>
      <div class='group-editor__title'>New Group</div>
      <div class='forms'>
        <%= f.label :name, "Group Name" %>
        <%= f.text_field :name %>
      </div>
      <div class='forms'>
        <%= f.label :body, "About this Group" %>
        <%= f.text_field :body %>
      </div>
      <div class='forms_checkbox'>
        <%= f.check_box :private, {}, 'true', 'false' %>
        <%= f.label :private, "Make this group Private?" %>
        <p>In 'Private' groups, only members can read articles</p>
      </div>
      <div class='actions'>
        <%= f.submit "Create" %>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<%= render partial: 'groups/sidebar' %>

<div class='group-body'>
  <ul class="nav nav-tabs">
    <li class="active">
      <a href="#tab1" class="nav-link" data-toggle="tab">
        <%= fa_icon 'file-text' %> Articles
      </a>
    </li>
    <li>
      <a href="#tab2" class="nav-link" data-toggle="tab">
        <%= fa_icon 'users' %> Members
      </a>
    </li>
  </ul>

  <div class="tab-content">
    <div id="tab1" class="tab-pane active">
      <!-- グループに紐づけて記事を書く場合のボタン -->
      <%= link_to  new_article_path(group_id: @group.id),
        method: :get,
        class: 'post-article-button' do
      %>
         <%= fa_icon 'pencil-square-o' %> Post New Article in Group
      <% end %>
      <!-- グループに紐づけられた記事の一覧 -->
      <% if @group.articles.present? %>
        <%= render partial: 'articles/result',
          locals: { articles: @group.articles.order("updated_at DESC").page(params[:page]).per(10), keyword: nil } %>
      <% else %>
        <p>There are no articles in this group</p>
      <% end %>
    </div>
    <div id="tab2" class="tab-pane">
      <!-- privateがtrueならメンバーのinviteぺージへのリンクを表示 -->
      <% if @group.private == true %>
        <%= link_to new_group_group_user_path(@group, @group_user) do %>
          <%= fa_icon 'plus-square' %> Invite New Member
        <% end %>
      <% end %>
      <!-- メンバーの一覧表示 -->
      <div>
        <% @group.users.each do |user| %>
          <div class='group__member'>
            <%= image_tag user.image.to_s, class: 'group__member__image' %>
            <%= link_to user.username, user_path(user.id), class: 'group__member__name'%>
          </div>
        <% end %>
      </div>
    </div>
  </div>