config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  devise_for :users
  resources :users, only: [:show]

  resources :articles do
    collection do
      get :search
    end
    resources :comments, only: [:new, :edit, :create, :update, :destroy] do
      resources :comment_likes, only: [:create, :destroy]
    end
    resources :stocks, only: [:create, :destroy]
    resources :article_likes, only: [:create, :destroy]
  end

  resources :groups do
    resources :group_users, only: [:new, :create, :update, :destroy]
    resources :managers, only: [:update] do
      collection do
        get :change_manager
      end
    end
  end

  match 'tags/:tag', to: 'articles#index', as: :tag, via: [:get, :post]
  get 'tags', to: 'tags#index'

  post 'api_markdown' => 'articles#api_markdown'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true, uniqueness: true
  validates :slack_name,
            presence: true,
            uniqueness: true,
            format: { with: /\@/,
                      message: 'should start with @' }

  scope :searched_by_name, ->(keyword) { where('username LIKE(?)', "%#{keyword}%") }
  scope :group_manager, ->(group_manager_id) { find_by('id = ?', group_manager_id) }

  mount_uploader :image, ImageUploader

  def belonging_groups_without_master
   Group.without_master_joined_by(self)
  end

  def not_belonging_groups
    Group.all - groups
  end

  def not_belonging_public_groups
    not_belonging_groups.select { |group| group.private == false }
  end

  def already_joined_in_master_team?
    GroupUser.find_by(user_id: id, group_id: Group::MASTER_GROUP_ID).present?
  end

  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :stocks, dependent: :destroy

  has_many :group_users
  has_many :groups, through: :group_users

  has_many :article_likes, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_params

  def show
    @user = User.find(user_params[:id])
    stocks = Stock.where(user_id: @user.id)
    stocked_articles_ids = stocks.map(&:article_id)
    @stocked_articles = Article.where(id: stocked_articles_ids)
  end

  private

  def user_params
    params
  end
end

app/views/users/change_manager.html.erb
<h1><%= @group.name %>の管理者を変更</h1>
<div>
  <%= form_tag( group_change_manager_path(@group.id), method: :get) do %>
    <input name="keyword" placeholder="ユーザーを名前で検索" type="text">
      <button title="検索" type="submit">
      </button>
    </input>
  <% end %>
</div>

<div>
  <% @users.each do |user| %>
    <% if @group.users.include?(user) %>
      <%= user.name %>
      <%= user.email %>
      <% if user.id == @group.manager_id %>
        <span>現管理人</span><br>
      <% else %>
        <%= form_for @group do |f| %>
          <%= f.hidden_field :manager_id, :value => user.id %>
          <%= f.submit "管理者にする" , data: { confirm: "本当に管理者を#{user.name}に変更しますか？" }%><br>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/users/search.html.erb
<h1><%= @group.name %>にメンバーを追加</h1>
<div>
  <%= form_tag( group_users_search_path(@group.id), method: :get) do %>
    <input name="keyword" placeholder="ユーザーを名前で検索" type="text">
      <button title="検索" type="submit">
      </button>
    </input>
  <% end %>
</div>

<div>
  <% @users.each do |user| %>

    <%= user.name %><br>
    <%= user.email %><br>
    <% if GroupUser.exists?(user_id: user.id, group_id: @group.id) %>
      <span>すでに参加しています</span>
    <% else %>
      <%= form_for [@group, @group_user] do |f| %>
        <%= f.hidden_field :user_id, :value => user.id %>
        <%= f.hidden_field :group_id, :value => @group.id %>


        <%= f.submit "招待する" %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class='user-sidebar'>
  <div class='user-sidebar__header'>
    <%= image_tag @user.image.to_s, class: 'user__image' %>
    <div class='user__name'>
      <%= @user.username %>
    </div>
  </div>
  <div class='user__contributions'>
    <div class='user__article-count user__contribution'>
      <div class='user__contribution__label'>Articles</div>
      <div class='user__contribution__count'><%= @user.articles.length %></div>
    </div>
    <div class='user__stock-count user__contribution'>
      <div class='user__contribution__label'>Stocks</div>
      <div class='user__contribution__count'><%= @stocked_articles.length %></div>
    </div>
    <div class='user__comment-count user__contribution'>
      <div class='user__contribution__label'>Comments</div>
      <div class='user__contribution__count'><%= @user.comments.length %></div>
    </div>
  </div>
  <div class='user-sidebar__footer'>
    <% if @user == current_user %>
      <%= link_to "Edit",
        edit_user_registration_path,
        method: :get,
        class: 'user__edit-button'
      %>
    <% end %>
  </div>
</div>
<div class='user-page__body'>
  <ul class="nav nav-tabs">
    <li class="active">
      <a href="#article-tab" class="nav-link" data-toggle="tab">
        Articles
      </a>
    </li>
    <li>
      <a href="#stock-tab" class="nav-link" data-toggle="tab">
        Stocks
      </a>
    </li>
    <li>
      <a href="#comment-tab" class="nav-link" data-toggle="tab">
        Comments
      </a>
    </li>
  </ul>
  <div class="tab-content">
    <div id="article-tab" class="tab-pane active">
      <% if @user.articles.present? %>
          <%= render partial: 'articles/result',
            locals: { articles: @user
                                  .articles
                                  .order("updated_at DESC")
                                  .page(params[:page])
                                  .per(10),
                      keyword: nil
                    }
          %>
      <% else %>
        <div>There are no articles stocked </div>
      <% end %>
    </div>
    <div id="stock-tab" class="tab-pane">
      <% if @stocked_articles.present? %>
        <%= render partial: 'articles/result',
          locals: { articles: @stocked_articles
                                .order("updated_at DESC")
                                .page(params[:page])
                                .per(10),
                    keyword: nil
                  }
        %>
      <% else %>
        <div>There are no articles stocked </div>
      <% end %>
    </div>
    <div id="comment-tab" class="tab-pane">
      <% if Article.commented_by(current_user).present? %>
        <%= render partial: 'articles/result',
          locals: { articles: Article
                                .commented_by(current_user)
                                .order("updated_at DESC")
                                .page(params[:page])
                                .per(10),
                    keyword: nil
                  }
        %>
      <% else %>
        <div>There are no articles commented </div>
      <% end %>
    </div>
  </div>
</div>